org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.10
mod_id=projecte_soulstone_1785817675
mod_name=ProjectE Soulstone
mod_version=1.1.0
mod_group_id=cn.autoforged.projecte_soulstone_1785817675
mod_authors=2154989258@qq.com
mod_license=All Rights Reserved
